## Gather

In [466]:
import pandas as pd
import numpy as np
pd.options.display.max_columns = 50
import json
import requests
from io import StringIO
from urllib.request import Request, urlopen
import re

In [467]:
#gather data from twitter-archive-enhanced.csv
df_twitter_archive_enhanced = pd.read_csv('https://d17h27t6h515a5.cloudfront.net/topher/2017/August/59a4e958_twitter-archive-enhanced/twitter-archive-enhanced.csv')

In [468]:
#gather data from image-predictions.tsv
url_image_predictions = "https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv"
response_image_predictions = requests.get(url_image_predictions).text
df_image_predictions = pd.read_csv(StringIO(response_image_predictions), sep="\t")

In [469]:
#gather data from tweet_json.txt. I got this file using Twitter API 
with open ("tweet_json.txt") as file:
    data = [json.loads(line) for line in file]
df_tweet_json = pd.DataFrame(data)

## Assess

In [470]:
df_twitter_archive_enhanced

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2351,666049248165822465,NaN,NaN,2015-11-16 00:24:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a 1949 1st generation vulpix. Enj...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666049248...,5,10,None,None,None,None,None
2352,666044226329800704,NaN,NaN,2015-11-16 00:04:52 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a purebred Piers Morgan. Loves to Netf...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666044226...,6,10,a,None,None,None,None
2353,666033412701032449,NaN,NaN,2015-11-15 23:21:54 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a very happy pup. Big fan of well-main...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666033412...,9,10,a,None,None,None,None
2354,666029285002620928,NaN,NaN,2015-11-15 23:05:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a western brown Mitsubishi terrier. Up...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666029285...,7,10,a,None,None,None,None
2355,666020888022790149,NaN,NaN,2015-11-15 22:32:08 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a Japanese Irish Setter. Lost eye...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666020888...,8,10,None,None,None,None,None

In [471]:
df_image_predictions

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True
...,...,...,...,...,...,...,...,...,...,...,...,...
2070,891327558926688256,https://pbs.twimg.com/media/DF6hr6BUMAAzZgT.jpg,2,basset,0.555712,True,English_springer,0.225770,True,German_short-haired_pointer,0.175219,True
2071,891689557279858688,https://pbs.twimg.com/media/DF_q7IAWsAEuuN8.jpg,1,paper_towel,0.170278,False,Labrador_retriever,0.168086,True,spatula,0.040836,False
2072,891815181378084864,https://pbs.twimg.com/media/DGBdLU1WsAANxJ9.jpg,1,Chihuahua,0.716012,True,malamute,0.078253,True,kelpie,0.031379,True
2073,892177421306343426,https://pbs.twimg.com/media/DGGmoV4XsAAUL6n.jpg,1,Chihuahua,0.323581,True,Pekinese,0.090647,True,papillon,0.068957,True
2074,892420643555336193,https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg,1,orange,0.097049,False,bagel,0.085851,False,banana,0.076110,False

In [472]:
df_tweet_json

,created_at,id,id_str,full_text,truncated,display_text_range,entities,extended_entities,source,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,in_reply_to_screen_name,user,geo,coordinates,place,contributors,is_quote_status,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,possibly_sensitive_appealable,lang,retweeted_status,quoted_status_id,quoted_status_id_str,quoted_status_permalink,quoted_status
0,Tue Aug 01 16:23:56 +0000 2017,892420643555336193,892420643555336193,This is Phineas. He's a mystical boy. Only eve...,False,"[0, 85]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 892420639486877696, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,7373,35072,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN
1,Tue Aug 01 00:17:27 +0000 2017,892177421306343426,892177421306343426,This is Tilly. She's just checking pup on you....,False,"[0, 138]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 892177413194625024, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,5494,30366,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN
2,Mon Jul 31 00:18:03 +0000 2017,891815181378084864,891815181378084864,This is Archie. He is a rare Norwegian Pouncin...,False,"[0, 121]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 891815175371796480, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,3632,22829,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN
3,Sun Jul 30 15:58:51 +0000 2017,891689557279858688,891689557279858688,This is Darla. She commenced a snooze mid meal...,False,"[0, 79]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 891689552724799489, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,7550,38342,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN
4,Sat Jul 29 16:00:24 +0000 2017,891327558926688256,891327558926688256,This is Franklin. He would like you to stop ca...,False,"[0, 138]","{'hashtags': [{'text': 'BarkWeek', 'indices': ...","{'media': [{'id': 891327551943041024, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,8137,36622,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2325,Mon Nov 16 00:24:50 +0000 2015,666049248165822465,666049248165822465,Here we have a 1949 1st generation vulpix. Enj...,False,"[0, 120]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666049244999131136, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,38,94,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN
2326,Mon Nov 16 00:04:52 +0000 2015,666044226329800704,666044226329800704,This is a purebred Piers Morgan. Loves to Netf...,False,"[0, 137]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666044217047650304, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,122,260,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN
2327,Sun Nov 15 23:21:54 +0000 2015,666033412701032449,666033412701032449,Here is a very happy pup. Big fan of well-main...,False,"[0, 130]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666033409081393153, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,39,107,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN
2328,Sun Nov 15 23:05:30 +0000 2015,666029285002620928,666029285002620928,This is a western brown Mitsubishi terrier. Up...,False,"[0, 139]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666029276303482880, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,41,118,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN
2329,Sun Nov 15 22:32:08 +0000 2015,666020888022790149,666020888022790149,Here we have a Japanese Irish Setter. Lost eye...,False,"[0, 131]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 666020881337073664, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,444,2345,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN

In [473]:
df_twitter_archive_enhanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   tweet_id                    2356 non-null   int64
 1   in_reply_to_status_id       78 non-null     float64
 2   in_reply_to_user_id         78 non-null     float64
 3   timestamp                   2356 non-null   object
 4   source                      2356 non-null   object
 5   text                        2356 non-null   object
 6   retweeted_status_id         181 non-null    float64
 7   retweeted_status_user_id    181 non-null    float64
 8   retweeted_status_timestamp  181 non-null    object
 9   expanded_urls               2297 non-null   object
 10  rating_numerator            2356 non-null   int64
 11  rating_denominator          2356 non-null   int64
 12  name                        2356 non-null   object
 13  doggo                       2356 non-null   object
 14  floofer                     2356 non-null   object
 15  pupper                      2356 non-null   object
 16  puppo                       2356 non-null   object
dtypes: float64(4), int64(3), object(10)
memory usage: 313.0+ KB

In [474]:
df_image_predictions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tweet_id  2075 non-null   int64
 1   jpg_url   2075 non-null   object
 2   img_num   2075 non-null   int64
 3   p1        2075 non-null   object
 4   p1_conf   2075 non-null   float64
 5   p1_dog    2075 non-null   bool
 6   p2        2075 non-null   object
 7   p2_conf   2075 non-null   float64
 8   p2_dog    2075 non-null   bool
 9   p3        2075 non-null   object
 10  p3_conf   2075 non-null   float64
 11  p3_dog    2075 non-null   bool
dtypes: bool(3), float64(3), int64(2), object(4)
memory usage: 152.1+ KB

In [475]:
df_tweet_json.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2330 entries, 0 to 2329
Data columns (total 32 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   created_at                     2330 non-null   object
 1   id                             2330 non-null   int64
 2   id_str                         2330 non-null   object
 3   full_text                      2330 non-null   object
 4   truncated                      2330 non-null   bool
 5   display_text_range             2330 non-null   object
 6   entities                       2330 non-null   object
 7   extended_entities              2058 non-null   object
 8   source                         2330 non-null   object
 9   in_reply_to_status_id          77 non-null     float64
 10  in_reply_to_status_id_str      77 non-null     object
 11  in_reply_to_user_id            77 non-null     float64
 12  in_reply_to_user_id_str        77 non-null     object
 13  in_reply_to_screen_name        77 non-null     object
 14  user                           2330 non-null   object
 15  geo                            0 non-null      object
 16  coordinates                    0 non-null      object
 17  place                          1 non-null      object
 18  contributors                   0 non-null      object
 19  is_quote_status                2330 non-null   bool
 20  retweet_count                  2330 non-null   int64
 21  favorite_count                 2330 non-null   int64
 22  favorited                      2330 non-null   bool
 23  retweeted                      2330 non-null   bool
 24  possibly_sensitive             2196 non-null   object
 25  possibly_sensitive_appealable  2196 non-null   object
 26  lang                           2330 non-null   object
 27  retweeted_status               163 non-null    object
 28  quoted_status_id               26 non-null     float64
 29  quoted_status_id_str           26 non-null     object
 30  quoted_status_permalink        26 non-null     object
 31  quoted_status                  24 non-null     object
dtypes: bool(4), float64(3), int64(3), object(22)
memory usage: 518.9+ KB

In [476]:
all_columns = pd.Series(list(df_twitter_archive_enhanced) + list(df_image_predictions))
all_columns[all_columns.duplicated()]

17    tweet_id
dtype: object

In [477]:
list(df_twitter_archive_enhanced)

['tweet_id',
 'in_reply_to_status_id',
 'in_reply_to_user_id',
 'timestamp',
 'source',
 'text',
 'retweeted_status_id',
 'retweeted_status_user_id',
 'retweeted_status_timestamp',
 'expanded_urls',
 'rating_numerator',
 'rating_denominator',
 'name',
 'doggo',
 'floofer',
 'pupper',
 'puppo']

In [478]:
df_twitter_archive_enhanced[df_twitter_archive_enhanced['expanded_urls'].isnull()]

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
30,886267009285017600,8.862664e+17,2.281182e+09,2017-07-15 16:51:35 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@NonWhiteHat @MayhewMayhem omg hello tanner yo...,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
55,881633300179243008,8.816070e+17,4.738443e+07,2017-07-02 21:58:53 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@roushfenway These are good dogs but 17/10 is ...,NaN,NaN,NaN,NaN,17,10,None,None,None,None,None
64,879674319642796034,8.795538e+17,3.105441e+09,2017-06-27 12:14:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@RealKentMurphy 14/10 confirmed,NaN,NaN,NaN,NaN,14,10,None,None,None,None,None
113,870726314365509632,8.707262e+17,1.648776e+07,2017-06-02 19:38:25 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@ComplicitOwl @ShopWeRateDogs &gt;10/10 is res...,NaN,NaN,NaN,NaN,10,10,None,None,None,None,None
148,863427515083354112,8.634256e+17,7.759620e+07,2017-05-13 16:15:35 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@Jack_Septic_Eye I'd need a few more pics to p...,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
179,857214891891077121,8.571567e+17,1.806710e+08,2017-04-26 12:48:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@Marc_IRL pixelated af 12/10,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
185,856330835276025856,NaN,NaN,2017-04-24 02:15:55 +0000,"<a href=""http://twitter.com/download/iphone"" r...",RT @Jenna_Marbles: @dog_rates Thanks for ratin...,8.563302e+17,66699013.0,2017-04-24 02:13:14 +0000,NaN,14,10,None,None,None,None,None
186,856288084350160898,8.562860e+17,2.792810e+08,2017-04-23 23:26:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@xianmcguire @Jenna_Marbles Kardashians wouldn...,NaN,NaN,NaN,NaN,14,10,None,None,None,None,None
188,855862651834028034,8.558616e+17,1.943518e+08,2017-04-22 19:15:32 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@dhmontgomery We also gave snoop dogg a 420/10...,NaN,NaN,NaN,NaN,420,10,None,None,None,None,None
189,855860136149123072,8.558585e+17,1.361572e+07,2017-04-22 19:05:32 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@s8n You tried very hard to portray this good ...,NaN,NaN,NaN,NaN,666,10,None,None,None,None,None
218,850333567704068097,8.503288e+17,2.195506e+07,2017-04-07 13:04:55 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@markhoppus MARK THAT DOG HAS SEEN AND EXPERIE...,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
228,848213670039564288,8.482121e+17,4.196984e+09,2017-04-01 16:41:12 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Jerry just apuppologized to me. He said there ...,NaN,NaN,NaN,NaN,11,10,None,None,None,None,None
234,847617282490613760,8.476062e+17,4.196984e+09,2017-03-31 01:11:22 +0000,"<a href=""http://twitter.com/download/iphone"" r...",.@breaannanicolee PUPDATE: Cannon has a heart ...,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
274,840698636975636481,8.406983e+17,8.405479e+17,2017-03-11 22:59:09 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@0_kelvin_0 &gt;10/10 is reserved for puppos s...,NaN,NaN,NaN,NaN,10,10,None,None,None,None,None
290,838150277551247360,8.381455e+17,2.195506e+07,2017-03-04 22:12:52 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@markhoppus 182/10,NaN,NaN,NaN,NaN,182,10,None,None,None,None,None
291,838085839343206401,8.380855e+17,2.894131e+09,2017-03-04 17:56:49 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@bragg6of8 @Andy_Pace_ we are still looking fo...,NaN,NaN,NaN,NaN,15,10,None,None,None,None,None
313,835246439529840640,8.352460e+17,2.625958e+07,2017-02-24 21:54:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@jonnysun @Lin_Manuel ok jomny I know you're e...,NaN,NaN,NaN,NaN,960,0,None,None,None,None,None
342,832088576586297345,8.320875e+17,3.058208e+07,2017-02-16 04:45:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@docmisterio account started on 11/15/15,NaN,NaN,NaN,NaN,11,15,None,None,None,None,None
346,831926988323639298,8.319030e+17,2.068372e+07,2017-02-15 18:03:45 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@UNC can confirm 12/10,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
375,828361771580813312,NaN,NaN,2017-02-05 21:56:51 +0000,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",Beebop and Doobert should start a band 12/10 w...,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
387,826598799820865537,8.265984e+17,4.196984e+09,2017-02-01 01:11:25 +0000,"<a href=""http://twitter.com/download/iphone"" r...","I was going to do 007/10, but the joke wasn't ...",NaN,NaN,NaN,NaN,7,10,None,None,None,None,None
409,823333489516937216,8.233264e+17,1.582854e+09,2017-01-23 00:56:15 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@HistoryInPics 13/10,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
427,821153421864615936,8.211526e+17,1.132119e+08,2017-01-17 00:33:26 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@imgur for a polar bear tho I'd say 13/10 is a...,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
498,813130366689148928,8.131273e+17,4.196984e+09,2016-12-25 21:12:41 +0000,"<a href=""http://twitter.com/download/iphone"" r...",I've been informed by multiple sources that th...,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
513,811647686436880384,8.116272e+17,4.196984e+09,2016-12-21 19:01:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",PUPDATE: I've been informed that Augie was act...,NaN,NaN,NaN,NaN,11,10,None,None,None,None,None
570,801854953262350336,8.018543e+17,1.185634e+07,2016-11-24 18:28:13 +0000,"<a href=""http://twitter.com/download/iphone"" r...",.@NBCSports OMG THE TINY HAT I'M GOING TO HAVE...,NaN,NaN,NaN,NaN,11,10,None,None,None,None,None
576,800859414831898624,8.008580e+17,2.918590e+08,2016-11-22 00:32:18 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@SkyWilliams doggo simply protecting you from ...,NaN,NaN,NaN,NaN,11,10,None,doggo,None,None,None
611,797165961484890113,7.971238e+17,2.916630e+07,2016-11-11 19:55:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@JODYHiGHROLLER it may be an 11/10 but what do...,NaN,NaN,NaN,NaN,11,10,None,None,None,None,None
701,786051337297522688,7.727430e+17,7.305050e+17,2016-10-12 03:50:17 +0000,"<a href=""http://twitter.com/download/iphone"" r...",13/10 for breakdancing puppo @shibbnbot,NaN,NaN,NaN,NaN,13,10,None,None,None,None,puppo
707,785515384317313025,NaN,NaN,2016-10-10 16:20:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...","Today, 10/10, should be National Dog Rates Day",NaN,NaN,NaN,NaN,10,10,None,None,None,None,None
843,766714921925144576,7.667118e+17,4.196984e+09,2016-08-19 19:14:16 +0000,"<a href=""http://twitter.com/download/iphone"" r...",His name is Charley and he already has a new s...,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
857,763956972077010945,7.638652e+17,1.584641e+07,2016-08-12 04:35:10 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@TheEllenShow I'm not sure if you know this bu...,NaN,NaN,NaN,NaN,12,10,None,doggo,None,None,None
967,750381685133418496,7.501805e+17,4.717297e+09,2016-07-05 17:31:49 +0000,"<a href=""http://twitter.com/download/iphone"" r...",13/10 such a good doggo\n@spaghemily,NaN,NaN,NaN,NaN,13,10,None,doggo,None,None,None
1005,747651430853525504,7.476487e+17,4.196984e+09,2016-06-28 04:42:46 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Other pupper asked not to have his identity sh...,NaN,NaN,NaN,NaN,12,10,None,None,None,pupper,None
1080,738891149612572673,7.384119e+17,3.589728e+08,2016-06-04 00:32:32 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@mount_alex3 13/10,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
1295,707983188426153984,7.079801e+17,2.319108e+09,2016-03-10 17:35:20 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@serial @MrRoles OH MY GOD I listened to all o...,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
1345,704491224099647488,7.044857e+17,2.878549e+07,2016-03-01 02:19:31 +0000,"<a href=""http://twitter.com/download/iphone"" r...",13/10 hero af\n@ABC,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
1445,696518437233913856,NaN,NaN,2016-02-08 02:18:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Oh my god 10/10 for every little hot dog pupper,NaN,NaN,NaN,NaN,10,10,None,None,None,pupper,None
1446,696490539101908992,6.964887e+17,4.196984e+09,2016-02-08 00:27:39 +0000,"<a href=""http://twitter.com/download/iphone"" r...",After reading the comments I may have overesti...,NaN,NaN,NaN,NaN,1,10,None,None,None,None,None
1474,693644216740769793,6.936422e+17,4.196984e+09,2016-01-31 03:57:23 +0000,"<a href=""http://twitter.com/download/iphone"" r...",BREAKING PUPDATE: I've just been notified that...,NaN,NaN,NaN,NaN,10,10,None,None,None,None,None
1479,693582294167244802,6.935722e+17,1.198989e+09,2016-01-30 23:51:19 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Personally I'd give him an 11/10. Not sure why...,NaN,NaN,NaN,NaN,11,10,None,None,None,None,None
1497,692423280028966913,6.924173e+17,4.196984e+09,2016-01-27 19:05:49 +0000,"<a href=""http://twitter.com/download/iphone"" r...",PUPDATE: just noticed this dog has some extra ...,NaN,NaN,NaN,NaN,9,10,None,None,None,None,None
1523,690607260360429569,6.903413e+17,4.670367e+08,2016-01-22 18:49:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",12/10 @LightningHoltt,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
1598,686035780142297088,6.860340e+17,4.196984e+09,2016-01-10 04:04:10 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Yes I do realize a rating of 4/20 would've bee...,NaN,NaN,NaN,NaN,4,20,None,None,None,None,None
1605,685681090388975616,6.855479e+17,4.196984e+09,2016-01-09 04:34:45 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Jack deserves another round of applause. If yo...,NaN,NaN,NaN,NaN,14,10,None,None,None,None,None
1618,684969860808454144,6.849598e+17,4.196984e+09,2016-01-07 05:28:35 +0000,"<a href=""http://twitter.com/download/iphone"" r...","For those who claim this is a goat, u are wron...",NaN,NaN,NaN,NaN,5,10,None,None,None,None,None
1663,682808988178739200,6.827884e+17,4.196984e+09,2016-01-01 06:22:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...","I'm aware that I could've said 20/16, but here...",NaN,NaN,NaN,NaN,20,16,None,None,None,None,None
1689,681340665377193984,6.813394e+17,4.196984e+09,2015-12-28 05:07:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",I've been told there's a slight possibility he...,NaN,NaN,NaN,NaN,5,10,None,None,None,None,None
1774,678023323247357953,6.780211e+17,4.196984e+09,2015-12-19 01:25:31 +0000,"<a href=""http://twitter.com/download/iphone"" r...",After getting lost in Reese's eyes for several...,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
1819,676590572941893632,6.765883e+17,4.196984e+09,2015-12-15 02:32:17 +0000,"<a href=""http://twitter.com/download/iphone"" r...",After some outrage from the crowd. Bubbles is ...,NaN,NaN,NaN,NaN,7,10,None,None,None,None,None
1844,675849018447167488,6.758457e+17,4.196984e+09,2015-12-13 01:25:37 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This dog is being demoted to a 9/10 for not we...,NaN,NaN,NaN,NaN,9,10,None,None,None,None,None
1895,674742531037511680,6.747400e+17,4.196984e+09,2015-12-10 00:08:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Some clarification is required. The dog is sin...,NaN,NaN,NaN,NaN,11,10,None,None,None,None,None
1905,674606911342424069,6.744689e+17,4.196984e+09,2015-12-09 15:09:55 +0000,"<a href=""http://twitter.com/download/iphone"" r...",The 13/10 also takes into account this impecca...,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
1914,674330906434379776,6.658147e+17,1.637468e+07,2015-12-08 20:53:11 +0000,"<a href=""http://twitter.com/download/iphone"" r...",13/10\n@ABC7,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
1940,673716320723169284,6.737159e+17,4.196984e+09,2015-12-07 04:11:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",The millennials have spoken and we've decided ...,NaN,NaN,NaN,NaN,1,10,None,None,None,None,None
2038,671550332464455680,6.715449e+17,4.196984e+09,2015-12-01 04:44:10 +0000,"<a href=""http://twitter.com/download/iphone"" r...",After 22 minutes of careful deliberation this ...,NaN,NaN,NaN,NaN,1,10,None,None,None,None,None
2149,669684865554620416,6.693544e+17,4.196984e+09,2015-11-26 01:11:28 +0000,"<a href=""http://twitter.com/download/iphone"" r...",After countless hours of research and hundreds...,NaN,NaN,NaN,NaN,11,10,None,None,None,None,None
2189,668967877119254528,6.689207e+17,2.143566e+07,2015-11-24 01:42:25 +0000,"<a href=""http://twitter.com/download/iphone"" r...",12/10 good shit Bubka\n@wane15,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
2298,667070482143944705,6.670655e+17,4.196984e+09,2015-11-18 20:02:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",After much debate this dog is being upgraded t...,NaN,NaN,NaN,NaN,10,10,None,None,None,None,None

In [479]:
df_twitter_archive_enhanced.describe()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,retweeted_status_id,retweeted_status_user_id,rating_numerator,rating_denominator
count,2.356000e+03,7.800000e+01,7.800000e+01,1.810000e+02,1.810000e+02,2356.000000,2356.000000
mean,7.427716e+17,7.455079e+17,2.014171e+16,7.720400e+17,1.241698e+16,13.126486,10.455433
std,6.856705e+16,7.582492e+16,1.252797e+17,6.236928e+16,9.599254e+16,45.876648,6.745237
min,6.660209e+17,6.658147e+17,1.185634e+07,6.661041e+17,7.832140e+05,0.000000,0.000000
25%,6.783989e+17,6.757419e+17,3.086374e+08,7.186315e+17,4.196984e+09,10.000000,10.000000
50%,7.196279e+17,7.038708e+17,4.196984e+09,7.804657e+17,4.196984e+09,11.000000,10.000000
75%,7.993373e+17,8.257804e+17,4.196984e+09,8.203146e+17,4.196984e+09,12.000000,10.000000
max,8.924206e+17,8.862664e+17,8.405479e+17,8.874740e+17,7.874618e+17,1776.000000,170.000000

In [480]:
df_image_predictions.describe()

           tweet_id      img_num      p1_conf       p2_conf       p3_conf
count  2.075000e+03  2075.000000  2075.000000  2.075000e+03  2.075000e+03
mean   7.384514e+17     1.203855     0.594548  1.345886e-01  6.032417e-02
std    6.785203e+16     0.561875     0.271174  1.006657e-01  5.090593e-02
min    6.660209e+17     1.000000     0.044333  1.011300e-08  1.740170e-10
25%    6.764835e+17     1.000000     0.364412  5.388625e-02  1.622240e-02
50%    7.119988e+17     1.000000     0.588230  1.181810e-01  4.944380e-02
75%    7.932034e+17     1.000000     0.843855  1.955655e-01  9.180755e-02
max    8.924206e+17     4.000000     1.000000  4.880140e-01  2.734190e-01

In [481]:
df_twitter_archive_enhanced.source.value_counts()

<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>     2221
<a href="http://vine.co" rel="nofollow">Vine - Make a Scene</a>                          91
<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>                       33
<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>      11
Name: source, dtype: int64

In [482]:
df_tweet_json.source.value_counts()

<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>     2197
<a href="http://vine.co" rel="nofollow">Vine - Make a Scene</a>                          91
<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>                       32
<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>      10
Name: source, dtype: int64

In [483]:
df_twitter_archive_enhanced.name.value_counts()

None       745
a           55
Charlie     12
Cooper      11
Lucy        11
          ...
Tuco         1
Bayley       1
Barry        1
Oddie        1
Eevee        1
Name: name, Length: 957, dtype: int64

In [484]:
df_twitter_archive_enhanced[df_twitter_archive_enhanced.name == 'a']

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
56,881536004380872706,NaN,NaN,2017-07-02 15:32:16 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a pupper approaching maximum borkdrive...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/881536004...,14,10,a,None,None,pupper,None
649,792913359805018113,NaN,NaN,2016-10-31 02:17:31 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a perfect example of someone who has t...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/792913359...,13,10,a,None,None,None,None
801,772581559778025472,NaN,NaN,2016-09-04 23:46:12 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Guys this is getting so out of hand. We only r...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/772581559...,10,10,a,None,None,None,None
1002,747885874273214464,NaN,NaN,2016-06-28 20:14:22 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a mighty rare blue-tailed hammer sherk...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/747885874...,8,10,a,None,None,None,None
1004,747816857231626240,NaN,NaN,2016-06-28 15:40:07 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Viewer discretion is advised. This is a terrib...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/747816857...,4,10,a,None,None,None,None
1017,746872823977771008,NaN,NaN,2016-06-26 01:08:52 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a carrot. We only rate dogs. Please on...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/746872823...,11,10,a,None,None,None,None
1049,743222593470234624,NaN,NaN,2016-06-15 23:24:09 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a very rare Great Alaskan Bush Pupper....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/743222593...,12,10,a,None,None,pupper,None
1193,717537687239008257,NaN,NaN,2016-04-06 02:21:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",People please. This is a Deadly Mediterranean ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/717537687...,11,10,a,None,None,None,None
1207,715733265223708672,NaN,NaN,2016-04-01 02:51:22 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a taco. We only rate dogs. Please only...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/715733265...,10,10,a,None,None,None,None
1340,704859558691414016,NaN,NaN,2016-03-02 02:43:09 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a heartbreaking scene of an incredible...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/704859558...,10,10,a,None,None,pupper,None
1351,704054845121142784,NaN,NaN,2016-02-28 21:25:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a whole flock of puppers. 60/50 I'll ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/704054845...,60,50,a,None,None,None,None
1361,703079050210877440,NaN,NaN,2016-02-26 04:48:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Butternut Cumberfloof. It's not wind...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/703079050...,11,10,a,None,None,None,None
1368,702539513671897089,NaN,NaN,2016-02-24 17:04:07 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Wild Tuscan Poofwiggle. Careful not ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/702539513...,12,10,a,None,None,None,None
1382,700864154249383937,NaN,NaN,2016-02-20 02:06:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...","""Pupper is a present to world. Here is a bow f...",NaN,NaN,NaN,https://twitter.com/dog_rates/status/700864154...,12,10,a,None,None,pupper,None
1499,692187005137076224,NaN,NaN,2016-01-27 03:26:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a rare Arctic Wubberfloof. Unamused by...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/692187005...,12,10,a,None,None,None,None
1737,679530280114372609,NaN,NaN,2015-12-23 05:13:38 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Guys this really needs to stop. We've been ove...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/679530280...,7,10,a,None,None,None,None
1785,677644091929329666,NaN,NaN,2015-12-18 00:18:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a dog swinging. I really enjoyed it so...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/677644091...,11,10,a,None,None,None,None
1853,675706639471788032,NaN,NaN,2015-12-12 15:59:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Sizzlin Menorah spaniel from Brookly...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/675706639...,10,10,a,None,None,None,None
1854,675534494439489536,NaN,NaN,2015-12-12 04:35:48 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Seriously guys?! Only send in dogs. I only rat...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/675534494...,11,10,a,None,None,None,None
1877,675109292475830276,NaN,NaN,2015-12-11 00:26:12 +0000,"<a href=""http://twitter.com/download/iphone"" r...",C'mon guys. We've been over this. We only rate...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/675109292...,9,10,a,None,None,None,None
1878,675047298674663426,NaN,NaN,2015-12-10 20:19:52 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a fluffy albino Bacardi Columbia mix. ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/675047298...,11,10,a,None,None,None,None
1923,674082852460433408,NaN,NaN,2015-12-08 04:27:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Sagitariot Baklava mix. Loves her ne...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/674082852...,11,10,a,None,None,None,None
1941,673715861853720576,NaN,NaN,2015-12-07 04:09:13 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a heavily opinionated dog. Loves walls...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/673715861...,4,10,a,None,None,None,None
1955,673636718965334016,NaN,NaN,2015-12-06 22:54:44 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Lofted Aphrodisiac Terrier named Kip...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/673636718...,10,10,a,None,None,None,None
1994,672604026190569472,NaN,NaN,2015-12-04 02:31:10 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a baby Rand Paul. Curls for days. 11/1...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/672604026...,11,10,a,None,None,None,None
2034,671743150407421952,NaN,NaN,2015-12-01 17:30:22 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Tuscaloosa Alcatraz named Jacob (Yac...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/671743150...,11,10,a,None,None,None,None
2066,671147085991960577,NaN,NaN,2015-11-30 02:01:49 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Helvetica Listerine named Rufus. Thi...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/671147085...,9,10,a,None,None,None,None
2116,670427002554466305,NaN,NaN,2015-11-28 02:20:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Deciduous Trimester mix named Spork....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/670427002...,9,10,a,None,None,None,None
2125,670361874861563904,NaN,NaN,2015-11-27 22:01:40 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Rich Mahogany Seltzer named Cherokee...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/670361874...,9,10,a,None,None,None,None
2128,670303360680108032,NaN,NaN,2015-11-27 18:09:09 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Speckled Cauliflower Yosemite named ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/670303360...,9,10,a,None,None,None,None
2146,669923323644657664,NaN,NaN,2015-11-26 16:59:01 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a spotted Lipitor Rumpelstiltskin name...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/669923323...,10,10,a,None,None,None,None
2153,669661792646373376,NaN,NaN,2015-11-25 23:39:47 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a brave dog. Excellent free climber. T...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/669661792...,5,10,a,None,None,None,None
2161,669564461267722241,NaN,NaN,2015-11-25 17:13:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Coriander Baton Rouge named Alfredo....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/669564461...,10,10,a,None,None,None,None
2191,668955713004314625,NaN,NaN,2015-11-24 00:54:05 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Slovakian Helter Skelter Feta named ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/668955713...,10,10,a,None,None,None,None
2198,668815180734689280,NaN,NaN,2015-11-23 15:35:39 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a wild Toblerone from Papua New Guinea...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/668815180...,7,10,a,None,None,None,None
2211,668614819948453888,NaN,NaN,2015-11-23 02:19:29 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a horned dog. Much grace. Can jump ove...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/668614819...,7,10,a,None,None,None,None
2218,668507509523615744,NaN,NaN,2015-11-22 19:13:05 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Birmingham Quagmire named Chuk. Love...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/668507509...,10,10,a,None,None,None,None
2222,668466899341221888,NaN,NaN,2015-11-22 16:31:42 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a mother dog caring for her pups. Snaz...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/668466899...,4,10,a,None,None,None,None
2235,668171859951755264,NaN,NaN,2015-11-21 20:59:20 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Trans Siberian Kellogg named Alfonso...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/668171859...,7,10,a,None,None,None,None
2249,667861340749471744,NaN,NaN,2015-11-21 00:25:26 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Shotokon Macadamia mix named Cheryl....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/667861340...,9,10,a,None,None,None,None
2255,667773195014021121,NaN,NaN,2015-11-20 18:35:10 +0000,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",This is a rare Hungarian Pinot named Jessiga. ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/667773195...,8,10,a,None,None,None,None
2264,667538891197542400,NaN,NaN,2015-11-20 03:04:08 +0000,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",This is a southwest Coriander named Klint. Hat...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/667538891...,9,10,a,None,None,None,None
2273,667470559035432960,NaN,NaN,2015-11-19 22:32:36 +0000,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",This is a northern Wahoo named Kohl. He runs t...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/667470559...,11,10,a,None,None,None,None
2287,667177989038297088,NaN,NaN,2015-11-19 03:10:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a Dasani Kingfisher from Maine. His na...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/667177989...,8,10,a,None,None,None,None
2304,666983947667116034,NaN,NaN,2015-11-18 14:18:59 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a curly Ticonderoga named Pepe. No fee...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666983947...,11,10,a,None,None,None,None
2311,666781792255496192,NaN,NaN,2015-11-18 00:55:42 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a purebred Bacardi named Octaviath. Ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666781792...,10,10,a,None,None,None,None
2314,666701168228331520,NaN,NaN,2015-11-17 19:35:19 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a golden Buckminsterfullerene named Jo...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666701168...,8,10,a,None,None,None,None
2327,666407126856765440,NaN,NaN,2015-11-17 00:06:54 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a southern Vesuvius bumblegruff. Can d...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666407126...,7,10,a,None,None,None,None
2334,666293911632134144,NaN,NaN,2015-11-16 16:37:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a funny dog. Weird toes. Won't come do...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666293911...,3,10,a,None,None,None,None
2347,666057090499244032,NaN,NaN,2015-11-16 00:55:59 +0000,"<a href=""http://twitter.com/download/iphone"" r...",My oh my. This is a rare blond Canadian terrie...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666057090...,9,10,a,None,None,None,None
2348,666055525042405380,NaN,NaN,2015-11-16 00:49:46 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a Siberian heavily armored polar bear ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666055525...,10,10,a,None,None,None,None
2350,666050758794694657,NaN,NaN,2015-11-16 00:30:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a truly beautiful English Wilson Staff...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666050758...,10,10,a,None,None,None,None
2352,666044226329800704,NaN,NaN,2015-11-16 00:04:52 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a purebred Piers Morgan. Loves to Netf...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666044226...,6,10,a,None,None,None,None
2353,666033412701032449,NaN,NaN,2015-11-15 23:21:54 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a very happy pup. Big fan of well-main...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666033412...,9,10,a,None,None,None,None
2354,666029285002620928,NaN,NaN,2015-11-15 23:05:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a western brown Mitsubishi terrier. Up...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666029285...,7,10,a,None,None,None,None

In [485]:
df_twitter_archive_enhanced[df_twitter_archive_enhanced.name.duplicated()]

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
7,890729181411237888,NaN,NaN,2017-07-28 00:22:40 +0000,"<a href=""http://twitter.com/download/iphone"" r...",When you watch your owner call another dog a g...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890729181...,13,10,None,None,None,None,None
12,889665388333682689,NaN,NaN,2017-07-25 01:55:32 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here's a puppo that seems to be on the fence a...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889665388...,13,10,None,None,None,None,puppo
23,887473957103951883,NaN,NaN,2017-07-19 00:47:34 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Canela. She attempted some fancy porch...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887473957...,13,10,Canela,None,None,None,None
24,887343217045368832,NaN,NaN,2017-07-18 16:08:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",You may not have known you needed to see this ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887343217...,13,10,None,None,None,None,None
25,887101392804085760,NaN,NaN,2017-07-18 00:07:08 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This... is a Jubilant Antarctic House Bear. We...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/887101392...,12,10,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2351,666049248165822465,NaN,NaN,2015-11-16 00:24:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a 1949 1st generation vulpix. Enj...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666049248...,5,10,None,None,None,None,None
2352,666044226329800704,NaN,NaN,2015-11-16 00:04:52 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a purebred Piers Morgan. Loves to Netf...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666044226...,6,10,a,None,None,None,None
2353,666033412701032449,NaN,NaN,2015-11-15 23:21:54 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a very happy pup. Big fan of well-main...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666033412...,9,10,a,None,None,None,None
2354,666029285002620928,NaN,NaN,2015-11-15 23:05:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a western brown Mitsubishi terrier. Up...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666029285...,7,10,a,None,None,None,None
2355,666020888022790149,NaN,NaN,2015-11-15 22:32:08 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a Japanese Irish Setter. Lost eye...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666020888...,8,10,None,None,None,None,None

In [486]:
#Most of the time denominator is 10 but sometimes has another number -- Score not valid
df_twitter_archive_enhanced.rating_denominator.value_counts()

10     2333
11        3
50        3
80        2
20        2
2         1
16        1
40        1
70        1
15        1
90        1
110       1
120       1
130       1
150       1
170       1
7         1
0         1
Name: rating_denominator, dtype: int64

In [487]:
#only three denominator value are less than 10
df_twitter_archive_enhanced[df_twitter_archive_enhanced.rating_denominator < 10].rating_denominator

313     0
516     7
2335    2
Name: rating_denominator, dtype: int64

In [488]:
#numerator value are less than 10
df_twitter_archive_enhanced[df_twitter_archive_enhanced.rating_numerator < 10].rating_numerator

45      5
229     6
315     0
387     7
462     7
       ..
2351    5
2352    6
2353    9
2354    7
2355    8
Name: rating_numerator, Length: 440, dtype: int64

In [582]:
#check number of nulls of expanded_urls
df_twitter_archive_enhanced.expanded_urls.isnull().value_counts()

False    2297
True       59
Name: expanded_urls, dtype: int64

In [583]:
df_twitter_archive_enhanced[df_twitter_archive_enhanced.expanded_urls.isnull() == True]

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
30,886267009285017600,8.862664e+17,2.281182e+09,2017-07-15 16:51:35 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@NonWhiteHat @MayhewMayhem omg hello tanner yo...,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
55,881633300179243008,8.816070e+17,4.738443e+07,2017-07-02 21:58:53 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@roushfenway These are good dogs but 17/10 is ...,NaN,NaN,NaN,NaN,17,10,None,None,None,None,None
64,879674319642796034,8.795538e+17,3.105441e+09,2017-06-27 12:14:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@RealKentMurphy 14/10 confirmed,NaN,NaN,NaN,NaN,14,10,None,None,None,None,None
113,870726314365509632,8.707262e+17,1.648776e+07,2017-06-02 19:38:25 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@ComplicitOwl @ShopWeRateDogs &gt;10/10 is res...,NaN,NaN,NaN,NaN,10,10,None,None,None,None,None
148,863427515083354112,8.634256e+17,7.759620e+07,2017-05-13 16:15:35 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@Jack_Septic_Eye I'd need a few more pics to p...,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
179,857214891891077121,8.571567e+17,1.806710e+08,2017-04-26 12:48:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@Marc_IRL pixelated af 12/10,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
185,856330835276025856,NaN,NaN,2017-04-24 02:15:55 +0000,"<a href=""http://twitter.com/download/iphone"" r...",RT @Jenna_Marbles: @dog_rates Thanks for ratin...,8.563302e+17,66699013.0,2017-04-24 02:13:14 +0000,NaN,14,10,None,None,None,None,None
186,856288084350160898,8.562860e+17,2.792810e+08,2017-04-23 23:26:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@xianmcguire @Jenna_Marbles Kardashians wouldn...,NaN,NaN,NaN,NaN,14,10,None,None,None,None,None
188,855862651834028034,8.558616e+17,1.943518e+08,2017-04-22 19:15:32 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@dhmontgomery We also gave snoop dogg a 420/10...,NaN,NaN,NaN,NaN,420,10,None,None,None,None,None
189,855860136149123072,8.558585e+17,1.361572e+07,2017-04-22 19:05:32 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@s8n You tried very hard to portray this good ...,NaN,NaN,NaN,NaN,666,10,None,None,None,None,None
218,850333567704068097,8.503288e+17,2.195506e+07,2017-04-07 13:04:55 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@markhoppus MARK THAT DOG HAS SEEN AND EXPERIE...,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
228,848213670039564288,8.482121e+17,4.196984e+09,2017-04-01 16:41:12 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Jerry just apuppologized to me. He said there ...,NaN,NaN,NaN,NaN,11,10,None,None,None,None,None
234,847617282490613760,8.476062e+17,4.196984e+09,2017-03-31 01:11:22 +0000,"<a href=""http://twitter.com/download/iphone"" r...",.@breaannanicolee PUPDATE: Cannon has a heart ...,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
274,840698636975636481,8.406983e+17,8.405479e+17,2017-03-11 22:59:09 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@0_kelvin_0 &gt;10/10 is reserved for puppos s...,NaN,NaN,NaN,NaN,10,10,None,None,None,None,None
290,838150277551247360,8.381455e+17,2.195506e+07,2017-03-04 22:12:52 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@markhoppus 182/10,NaN,NaN,NaN,NaN,182,10,None,None,None,None,None
291,838085839343206401,8.380855e+17,2.894131e+09,2017-03-04 17:56:49 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@bragg6of8 @Andy_Pace_ we are still looking fo...,NaN,NaN,NaN,NaN,15,10,None,None,None,None,None
313,835246439529840640,8.352460e+17,2.625958e+07,2017-02-24 21:54:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@jonnysun @Lin_Manuel ok jomny I know you're e...,NaN,NaN,NaN,NaN,960,0,None,None,None,None,None
342,832088576586297345,8.320875e+17,3.058208e+07,2017-02-16 04:45:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@docmisterio account started on 11/15/15,NaN,NaN,NaN,NaN,11,15,None,None,None,None,None
346,831926988323639298,8.319030e+17,2.068372e+07,2017-02-15 18:03:45 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@UNC can confirm 12/10,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
375,828361771580813312,NaN,NaN,2017-02-05 21:56:51 +0000,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",Beebop and Doobert should start a band 12/10 w...,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
387,826598799820865537,8.265984e+17,4.196984e+09,2017-02-01 01:11:25 +0000,"<a href=""http://twitter.com/download/iphone"" r...","I was going to do 007/10, but the joke wasn't ...",NaN,NaN,NaN,NaN,7,10,None,None,None,None,None
409,823333489516937216,8.233264e+17,1.582854e+09,2017-01-23 00:56:15 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@HistoryInPics 13/10,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
427,821153421864615936,8.211526e+17,1.132119e+08,2017-01-17 00:33:26 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@imgur for a polar bear tho I'd say 13/10 is a...,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
498,813130366689148928,8.131273e+17,4.196984e+09,2016-12-25 21:12:41 +0000,"<a href=""http://twitter.com/download/iphone"" r...",I've been informed by multiple sources that th...,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
513,811647686436880384,8.116272e+17,4.196984e+09,2016-12-21 19:01:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",PUPDATE: I've been informed that Augie was act...,NaN,NaN,NaN,NaN,11,10,None,None,None,None,None
570,801854953262350336,8.018543e+17,1.185634e+07,2016-11-24 18:28:13 +0000,"<a href=""http://twitter.com/download/iphone"" r...",.@NBCSports OMG THE TINY HAT I'M GOING TO HAVE...,NaN,NaN,NaN,NaN,11,10,None,None,None,None,None
576,800859414831898624,8.008580e+17,2.918590e+08,2016-11-22 00:32:18 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@SkyWilliams doggo simply protecting you from ...,NaN,NaN,NaN,NaN,11,10,None,doggo,None,None,None
611,797165961484890113,7.971238e+17,2.916630e+07,2016-11-11 19:55:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@JODYHiGHROLLER it may be an 11/10 but what do...,NaN,NaN,NaN,NaN,11,10,None,None,None,None,None
701,786051337297522688,7.727430e+17,7.305050e+17,2016-10-12 03:50:17 +0000,"<a href=""http://twitter.com/download/iphone"" r...",13/10 for breakdancing puppo @shibbnbot,NaN,NaN,NaN,NaN,13,10,None,None,None,None,puppo
707,785515384317313025,NaN,NaN,2016-10-10 16:20:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...","Today, 10/10, should be National Dog Rates Day",NaN,NaN,NaN,NaN,10,10,None,None,None,None,None
843,766714921925144576,7.667118e+17,4.196984e+09,2016-08-19 19:14:16 +0000,"<a href=""http://twitter.com/download/iphone"" r...",His name is Charley and he already has a new s...,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
857,763956972077010945,7.638652e+17,1.584641e+07,2016-08-12 04:35:10 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@TheEllenShow I'm not sure if you know this bu...,NaN,NaN,NaN,NaN,12,10,None,doggo,None,None,None
967,750381685133418496,7.501805e+17,4.717297e+09,2016-07-05 17:31:49 +0000,"<a href=""http://twitter.com/download/iphone"" r...",13/10 such a good doggo\n@spaghemily,NaN,NaN,NaN,NaN,13,10,None,doggo,None,None,None
1005,747651430853525504,7.476487e+17,4.196984e+09,2016-06-28 04:42:46 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Other pupper asked not to have his identity sh...,NaN,NaN,NaN,NaN,12,10,None,None,None,pupper,None
1080,738891149612572673,7.384119e+17,3.589728e+08,2016-06-04 00:32:32 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@mount_alex3 13/10,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
1295,707983188426153984,7.079801e+17,2.319108e+09,2016-03-10 17:35:20 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@serial @MrRoles OH MY GOD I listened to all o...,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
1345,704491224099647488,7.044857e+17,2.878549e+07,2016-03-01 02:19:31 +0000,"<a href=""http://twitter.com/download/iphone"" r...",13/10 hero af\n@ABC,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
1445,696518437233913856,NaN,NaN,2016-02-08 02:18:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Oh my god 10/10 for every little hot dog pupper,NaN,NaN,NaN,NaN,10,10,None,None,None,pupper,None
1446,696490539101908992,6.964887e+17,4.196984e+09,2016-02-08 00:27:39 +0000,"<a href=""http://twitter.com/download/iphone"" r...",After reading the comments I may have overesti...,NaN,NaN,NaN,NaN,1,10,None,None,None,None,None
1474,693644216740769793,6.936422e+17,4.196984e+09,2016-01-31 03:57:23 +0000,"<a href=""http://twitter.com/download/iphone"" r...",BREAKING PUPDATE: I've just been notified that...,NaN,NaN,NaN,NaN,10,10,None,None,None,None,None
1479,693582294167244802,6.935722e+17,1.198989e+09,2016-01-30 23:51:19 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Personally I'd give him an 11/10. Not sure why...,NaN,NaN,NaN,NaN,11,10,None,None,None,None,None
1497,692423280028966913,6.924173e+17,4.196984e+09,2016-01-27 19:05:49 +0000,"<a href=""http://twitter.com/download/iphone"" r...",PUPDATE: just noticed this dog has some extra ...,NaN,NaN,NaN,NaN,9,10,None,None,None,None,None
1523,690607260360429569,6.903413e+17,4.670367e+08,2016-01-22 18:49:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",12/10 @LightningHoltt,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
1598,686035780142297088,6.860340e+17,4.196984e+09,2016-01-10 04:04:10 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Yes I do realize a rating of 4/20 would've bee...,NaN,NaN,NaN,NaN,4,20,None,None,None,None,None
1605,685681090388975616,6.855479e+17,4.196984e+09,2016-01-09 04:34:45 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Jack deserves another round of applause. If yo...,NaN,NaN,NaN,NaN,14,10,None,None,None,None,None
1618,684969860808454144,6.849598e+17,4.196984e+09,2016-01-07 05:28:35 +0000,"<a href=""http://twitter.com/download/iphone"" r...","For those who claim this is a goat, u are wron...",NaN,NaN,NaN,NaN,5,10,None,None,None,None,None
1663,682808988178739200,6.827884e+17,4.196984e+09,2016-01-01 06:22:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...","I'm aware that I could've said 20/16, but here...",NaN,NaN,NaN,NaN,20,16,None,None,None,None,None
1689,681340665377193984,6.813394e+17,4.196984e+09,2015-12-28 05:07:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",I've been told there's a slight possibility he...,NaN,NaN,NaN,NaN,5,10,None,None,None,None,None
1774,678023323247357953,6.780211e+17,4.196984e+09,2015-12-19 01:25:31 +0000,"<a href=""http://twitter.com/download/iphone"" r...",After getting lost in Reese's eyes for several...,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
1819,676590572941893632,6.765883e+17,4.196984e+09,2015-12-15 02:32:17 +0000,"<a href=""http://twitter.com/download/iphone"" r...",After some outrage from the crowd. Bubbles is ...,NaN,NaN,NaN,NaN,7,10,None,None,None,None,None
1844,675849018447167488,6.758457e+17,4.196984e+09,2015-12-13 01:25:37 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This dog is being demoted to a 9/10 for not we...,NaN,NaN,NaN,NaN,9,10,None,None,None,None,None
1895,674742531037511680,6.747400e+17,4.196984e+09,2015-12-10 00:08:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Some clarification is required. The dog is sin...,NaN,NaN,NaN,NaN,11,10,None,None,None,None,None
1905,674606911342424069,6.744689e+17,4.196984e+09,2015-12-09 15:09:55 +0000,"<a href=""http://twitter.com/download/iphone"" r...",The 13/10 also takes into account this impecca...,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
1914,674330906434379776,6.658147e+17,1.637468e+07,2015-12-08 20:53:11 +0000,"<a href=""http://twitter.com/download/iphone"" r...",13/10\n@ABC7,NaN,NaN,NaN,NaN,13,10,None,None,None,None,None
1940,673716320723169284,6.737159e+17,4.196984e+09,2015-12-07 04:11:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",The millennials have spoken and we've decided ...,NaN,NaN,NaN,NaN,1,10,None,None,None,None,None
2038,671550332464455680,6.715449e+17,4.196984e+09,2015-12-01 04:44:10 +0000,"<a href=""http://twitter.com/download/iphone"" r...",After 22 minutes of careful deliberation this ...,NaN,NaN,NaN,NaN,1,10,None,None,None,None,None
2149,669684865554620416,6.693544e+17,4.196984e+09,2015-11-26 01:11:28 +0000,"<a href=""http://twitter.com/download/iphone"" r...",After countless hours of research and hundreds...,NaN,NaN,NaN,NaN,11,10,None,None,None,None,None
2189,668967877119254528,6.689207e+17,2.143566e+07,2015-11-24 01:42:25 +0000,"<a href=""http://twitter.com/download/iphone"" r...",12/10 good shit Bubka\n@wane15,NaN,NaN,NaN,NaN,12,10,None,None,None,None,None
2298,667070482143944705,6.670655e+17,4.196984e+09,2015-11-18 20:02:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",After much debate this dog is being upgraded t...,NaN,NaN,NaN,NaN,10,10,None,None,None,None,None

In [584]:
#verify rows where rating_numerator is less than 10
df_twitter_archive_enhanced[df_twitter_archive_enhanced.rating_numerator < 10].head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
45,883482846933004288,NaN,NaN,2017-07-08 00:28:19 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Bella. She hopes her smile made you sm...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/883482846...,5,10,Bella,None,None,None,None
229,848212111729840128,NaN,NaN,2017-04-01 16:35:01 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Jerry. He's doing a distinguished tong...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/848212111...,6,10,Jerry,None,None,None,None
315,835152434251116546,NaN,NaN,2017-02-24 15:40:31 +0000,"<a href=""http://twitter.com/download/iphone"" r...",When you're so blinded by your systematic plag...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/835152434...,0,10,None,None,None,None,None
387,826598799820865537,8.265984e+17,4.196984e+09,2017-02-01 01:11:25 +0000,"<a href=""http://twitter.com/download/iphone"" r...","I was going to do 007/10, but the joke wasn't ...",NaN,NaN,NaN,NaN,7,10,None,None,None,None,None
462,817502432452313088,NaN,NaN,2017-01-06 22:45:43 +0000,"<a href=""http://twitter.com/download/iphone"" r...",RT @dog_rates: Meet Herschel. He's slightly bi...,6.924173e+17,4.196984e+09,2016-01-27 18:42:06 +0000,https://twitter.com/dog_rates/status/692417313...,7,10,Herschel,None,None,pupper,None

In [585]:
#it can be seen that some text range start with 12 but if I count the characters the value value is the second
df_tweet_json.display_text_range.value_counts()

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1709, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

[0, 140]    251
[0, 139]    145
[0, 138]     79
[0, 137]     77
[0, 116]     59
           ...
[12, 56]      1
[10, 28]      1
[0, 21]       1
[0, 145]      1
[0, 148]      1
Name: display_text_range, Length: 143, dtype: int64

In [587]:
#making sure there are no values after 1 August 2017
df_twitter_archive_enhanced[df_twitter_archive_enhanced.timestamp > '2017-08-01 00:28:19 +0000'].head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None

In [588]:
#Check that there are tweet text that start by 13 display_text_range 
df_tweet_json[df_tweet_json.display_text_range.str[0] == 13]

,created_at,id,id_str,full_text,truncated,display_text_range,entities,extended_entities,source,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,in_reply_to_screen_name,user,geo,coordinates,place,contributors,is_quote_status,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,possibly_sensitive_appealable,lang,retweeted_status,quoted_status_id,quoted_status_id_str,quoted_status_permalink,quoted_status
54,Sun Jul 02 21:58:53 +0000 2017,881633300179243008,881633300179243008,@roushfenway These are good dogs but 17/10 is ...,False,"[13, 91]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,"<a href=""http://twitter.com/download/iphone"" r...",8.816070e+17,881607037314052101,47384430.0,47384430,roushfenway,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,7,115,False,False,NaN,NaN,en,NaN,NaN,NaN,NaN,NaN
328,Thu Feb 16 04:45:50 +0000 2017,832088576586297345,832088576586297345,@docmisterio account started on 11/15/15,False,"[13, 40]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,"<a href=""http://twitter.com/download/iphone"" r...",8.320875e+17,832087547559997440,30582082.0,30582082,docmisterio,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,2,61,False,False,NaN,NaN,en,NaN,NaN,NaN,NaN,NaN
558,Tue Nov 22 00:32:18 +0000 2016,800859414831898624,800859414831898624,@SkyWilliams doggo simply protecting you from ...,False,"[13, 105]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,"<a href=""http://twitter.com/download/iphone"" r...",8.008580e+17,800857954417262593,291859009.0,291859009,SkyWilliams,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,96,677,False,False,NaN,NaN,en,NaN,NaN,NaN,NaN,NaN
1056,Sat Jun 04 00:32:32 +0000 2016,738891149612572673,738891149612572673,@mount_alex3 13/10,False,"[13, 18]","{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,"<a href=""http://twitter.com/download/iphone"" r...",7.384119e+17,738411919896285185,358972768.0,358972768,mount_alex3,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,6,102,False,False,NaN,NaN,und,NaN,NaN,NaN,NaN,NaN

In [589]:
#it can gather the first part of the range of display_text_range
df_tweet_json.display_text_range.str[0].value_counts()

0     2307
13       4
12       3
5        2
16       2
14       2
27       1
23       1
17       1
15       1
7        1
30       1
28       1
22       1
18       1
10       1
Name: display_text_range, dtype: int64

In [590]:
#retweeted only shows False values
df_tweet_json.retweeted.value_counts()

False    2330
Name: retweeted, dtype: int64

In [591]:
#checking the field user which is a json
df_tweet_json.user[:][0]

{'id': 4196983835,
 'id_str': '4196983835',
 'name': 'WeRateDogs®',
 'screen_name': 'dog_rates',
 'location': 'links and things ➜',
 'description': 'Your Only Source For Professional Dog Ratings Instagram and Facebook ➜ WeRateDogs partnerships@weratedogs.com ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀',
 'url': 'https://t.co/6ytGi24QCk',
 'entities': {'url': {'urls': [{'url': 'https://t.co/6ytGi24QCk',
     'expanded_url': 'http://campsite.bio/weratedogs',
     'display_url': 'campsite.bio/weratedogs',
     'indices': [0, 23]}]},
  'description': {'urls': []}},
 'protected': False,
 'followers_count': 8964295,
 'friends_count': 17,
 'listed_count': 6371,
 'created_at': 'Sun Nov 15 21:41:29 +0000 2015',
 'favourites_count': 145799,
 'utc_offset': None,
 'time_zone': None,
 'geo_enabled': True,
 'verified': True,
 'statuses_count': 13464,
 'lang': None,
 'contributors_enabled': False,
 'is_translator': False,
 'is_translation_enabled': False,
 'profile_background_color': '000000',
 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
 'profile_background_tile': False,
 'profile_image_url': 'http://pbs.twimg.com/profile_images/1351720980972933122/I3MnYUdm_normal.jpg',
 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1351720980972933122/I3MnYUdm_normal.jpg',
 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/4196983835/1611883974',
 'profile_link_color': 'F5ABB5',
 'profile_sidebar_border_color': '000000',
 'profile_sidebar_fill_color': '000000',
 'profile_text_color': '000000',
 'profile_use_background_image': False,
 'has_extended_profile': False,
 'default_profile': False,
 'default_profile_image': False,
 'following': False,
 'follow_request_sent': False,
 'notifications': False,
 'translator_type': 'none'}

In [498]:
#checking that all user id are the same
new_array = []
for i in df_tweet_json['user']:
    print(i['id'])
    new_array.append(i['id'])

4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835

4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835
4196983835

In [499]:
result = new_array.count(new_array[0]) == len(new_array)
if result:
    print("all elements are equal")

all elements are equal

#### Quality
##### `df_twitter_archive_enhanced` table
- Delete columns with mostly null values: in_reply_to_status_id, in _reply_to_userr_id, retweeted_status_id, retweeted_status_user_id, retweeted_status_timestamp
- expanded_urls only 2297 not nulls
- timestamp is an object string and should be a date
- source is dirty it has a tag and href and all seem to be the same
- Create dog_stage a categorical variable for doggo, floofer, pupper, puppo and None it does not have a value. 
- There are  745 dogs named a
- Canela name is repeated
- May be change rating denominator and numerator to only one column
- Numerator and denominator ratings should not be less than 10
- Clean source and leave only the name of the source


##### `df_image_predictions` table
- Some capitalized and other lower case in columns p1, p2 and p3
- Missing record 2075 instead of 2356
- I don't understand img_num sometimes 1 and 2 

##### `df_tweet_json` table
- Change the column name id to tweet_id as the other tables
- id_str seem to be redundant
- source check if it is the same for all then delete as it doesn't add much information
- only 2330 rows
- delete columns: in_reply_to_status_id, in_reply_to_status_id_str, in_reply_to_user_id, in_reply_to_user_id_str, in_reply_to_screen_name, geo, coordinates, place, contributors, retweeted_status, quoted_status_id, quoted_status_permalink, quoted_status  
- delete source duplicated column

#### Tidiness
- create only one column for rating
- retweet_count_and favorite_count should be in `df_tweeter_archive_enhanced` table

## Clean

In [551]:
df_twitter_archive_enhanced_clean = df_twitter_archive_enhanced.copy()
df_image_predictions_clean = df_image_predictions.copy()
df_tweet_json_clean = df_tweet_json.copy()

### Redundant Data

#### `df_tweeter_archive_enhanced`: Delete columns with mostly null values

##### Define
Delete these columns : in_reply_to_status_id, in _reply_to_userr_id, retweeted_status_id, retweeted_status_user_id, retweeted_status_timestamp.

##### Code

In [552]:
df_twitter_archive_enhanced_clean.head(1)

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None

In [553]:
df_twitter_archive_enhanced_clean.drop(['in_reply_to_status_id', 'in_reply_to_user_id', 'retweeted_status_id', 'retweeted_status_user_id', 'retweeted_status_timestamp'], inplace=True, axis=1)

##### Test

In [554]:
df_twitter_archive_enhanced_clean.head(1)

,tweet_id,timestamp,source,text,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None

#### `df_twitter_archive_enhanced`: timestamp is an object string and should be a date

##### Define
change `timestamp` column: from `string` to `date` type.

##### Code

In [555]:
df_twitter_archive_enhanced_clean['timestamp'] = pd.to_datetime(df_twitter_archive_enhanced_clean['timestamp'])

##### Test

In [556]:
df_twitter_archive_enhanced_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tweet_id            2356 non-null   int64
 1   timestamp           2356 non-null   datetime64[ns, UTC]
 2   source              2356 non-null   object
 3   text                2356 non-null   object
 4   expanded_urls       2297 non-null   object
 5   rating_numerator    2356 non-null   int64
 6   rating_denominator  2356 non-null   int64
 7   name                2356 non-null   object
 8   doggo               2356 non-null   object
 9   floofer             2356 non-null   object
 10  pupper              2356 non-null   object
 11  puppo               2356 non-null   object
dtypes: datetime64[ns, UTC](1), int64(3), object(8)
memory usage: 221.0+ KB

#### `df_twitter_archive_enhanced`: Clean source and leave only the name of the source

##### Define
in `source` remove the tags and leave only the names.

##### Code

In [557]:
df_twitter_archive_enhanced_clean.source[0]

'<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>'

In [558]:
df_twitter_archive_enhanced_clean.source.value_counts()

<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>     2221
<a href="http://vine.co" rel="nofollow">Vine - Make a Scene</a>                          91
<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>                       33
<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>      11
Name: source, dtype: int64

In [559]:
df_twitter_archive_enhanced_clean['source'] = df_twitter_archive_enhanced_clean.source.str.extract('>([^;]*)<')

##### Test

In [560]:
df_twitter_archive_enhanced_clean.source.head()

0    Twitter for iPhone
1    Twitter for iPhone
2    Twitter for iPhone
3    Twitter for iPhone
4    Twitter for iPhone
Name: source, dtype: object

#### `df_twitter_archive_enhanced_clean`: Create dog_stage a categorical variable for doggo, floofer, pupper, puppo and None it does not have a value.

##### Define
create a new variable dog_stage and delete all other columns: doggo, floofer, pupper, puppo

##### Code

In [561]:
#create an array with all dog stages
dog_stage_array = []
for x in range(df_twitter_archive_enhanced_clean['doggo'].size):
    if df_twitter_archive_enhanced_clean['doggo'].iloc[x] != 'None':
        dog_stage_array.append('doggo')
    elif df_twitter_archive_enhanced_clean['floofer'].iloc[x] != 'None':
        dog_stage_array.append('floofer')
    elif df_twitter_archive_enhanced_clean['pupper'].iloc[x] != 'None':
        dog_stage_array.append('pupper')
    elif df_twitter_archive_enhanced_clean['puppo'].iloc[x] != 'None':
        dog_stage_array.append('puppo')
    else :
        dog_stage_array.append('None')

In [562]:
#create new column and add it to the dataframe
df_twitter_archive_enhanced_clean['dog_stage'] = pd.Series(dog_stage_array, index=df_twitter_archive_enhanced.index)

# To category
df_twitter_archive_enhanced_clean.dog_stage = df_twitter_archive_enhanced_clean.dog_stage.astype('category')

In [563]:
#delete unnecessary columns doggo, floofer, pupper, puppo
df_twitter_archive_enhanced_clean = df_twitter_archive_enhanced_clean.drop(['doggo', 'floofer', 'pupper', 'puppo'], axis=1)

##### Test

In [564]:
df_twitter_archive_enhanced_clean.head()

,tweet_id,timestamp,source,text,expanded_urls,rating_numerator,rating_denominator,name,dog_stage
0,892420643555336193,2017-08-01 16:23:56+00:00,Twitter for iPhone,This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None
1,892177421306343426,2017-08-01 00:17:27+00:00,Twitter for iPhone,This is Tilly. She's just checking pup on you....,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None
2,891815181378084864,2017-07-31 00:18:03+00:00,Twitter for iPhone,This is Archie. He is a rare Norwegian Pouncin...,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None
3,891689557279858688,2017-07-30 15:58:51+00:00,Twitter for iPhone,This is Darla. She commenced a snooze mid meal...,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None
4,891327558926688256,2017-07-29 16:00:24+00:00,Twitter for iPhone,This is Franklin. He would like you to stop ca...,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None

In [565]:
df_twitter_archive_enhanced_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tweet_id            2356 non-null   int64
 1   timestamp           2356 non-null   datetime64[ns, UTC]
 2   source              2356 non-null   object
 3   text                2356 non-null   object
 4   expanded_urls       2297 non-null   object
 5   rating_numerator    2356 non-null   int64
 6   rating_denominator  2356 non-null   int64
 7   name                2356 non-null   object
 8   dog_stage           2356 non-null   category
dtypes: category(1), datetime64[ns, UTC](1), int64(3), object(4)
memory usage: 149.9+ KB

### Tidiness

#### In `df_twitter_archive_enhanced_clean` create only one column for ratings

##### Define
Delete denominator column as most ratings are 10 and only three denominator values are less than 10. We will leave numerator ratings but more than 440 are less than 10 we will analyze the effect of droping them in the analysis section. As there will be only one column for rating we will change rating_numerator to rating only.

##### Code

In [566]:
# Note: axis=1 denotes that we are referring to a column, not a row
df_twitter_archive_enhanced_clean = df_twitter_archive_enhanced_clean.drop('rating_denominator', axis=1)

#rename rating_numerator to rating
df_twitter_archive_enhanced_clean = df_twitter_archive_enhanced_clean.rename(columns={'rating_numerator': 'rating'})

##### Test

In [567]:
# Confirm contact column is gone
df_twitter_archive_enhanced_clean.head()

,tweet_id,timestamp,source,text,expanded_urls,rating,name,dog_stage
0,892420643555336193,2017-08-01 16:23:56+00:00,Twitter for iPhone,This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,Phineas,None
1,892177421306343426,2017-08-01 00:17:27+00:00,Twitter for iPhone,This is Tilly. She's just checking pup on you....,https://twitter.com/dog_rates/status/892177421...,13,Tilly,None
2,891815181378084864,2017-07-31 00:18:03+00:00,Twitter for iPhone,This is Archie. He is a rare Norwegian Pouncin...,https://twitter.com/dog_rates/status/891815181...,12,Archie,None
3,891689557279858688,2017-07-30 15:58:51+00:00,Twitter for iPhone,This is Darla. She commenced a snooze mid meal...,https://twitter.com/dog_rates/status/891689557...,13,Darla,None
4,891327558926688256,2017-07-29 16:00:24+00:00,Twitter for iPhone,This is Franklin. He would like you to stop ca...,https://twitter.com/dog_rates/status/891327558...,12,Franklin,None

#### In columns p1, p2 and p3 in `df_image_predictions_clean` some capitalized and others lower case

##### Define
Let's lower case p1, p2 and p3 so that all are even

##### Code

In [568]:
df_image_predictions_clean[['p1', 'p2', 'p3']] = df_image_predictions_clean[['p1', 'p2', 'p3']].astype(str).apply(lambda x: x.str.lower())

##### Test

In [569]:
df_image_predictions_clean.head()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,welsh_springer_spaniel,0.465074,True,collie,0.156665,True,shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,german_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,rottweiler,0.243682,True,doberman,0.154629,True

#### In `df_tweet_json_clean` table change column name `id` to `tweet_id` as the other tables

##### Define
Change clumn name `id` to `tweet_id`.

##### Code

In [570]:
df_tweet_json_clean = df_tweet_json_clean.rename(columns={'id': 'tweet_id'})

##### Test

In [571]:
df_tweet_json_clean.head(1)

,created_at,tweet_id,id_str,full_text,truncated,display_text_range,entities,extended_entities,source,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,in_reply_to_screen_name,user,geo,coordinates,place,contributors,is_quote_status,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,possibly_sensitive_appealable,lang,retweeted_status,quoted_status_id,quoted_status_id_str,quoted_status_permalink,quoted_status
0,Tue Aug 01 16:23:56 +0000 2017,892420643555336193,892420643555336193,This is Phineas. He's a mystical boy. Only eve...,False,"[0, 85]","{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 892420639486877696, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,7373,35072,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN

#### display_text_range in `df_tweet_json` table is not uselful as a list better change to numerical variable and also change the column name to something more descriptive text_length

##### Define
pickup the right part of the range of list as the text length and rename column name to text_length

##### Code

In [572]:
df_tweet_json_clean.display_text_range = df_tweet_json_clean.display_text_range.str[1]
df_tweet_json_clean = df_tweet_json_clean.rename(columns = {'display_text_range' : 'text_length'})

##### Test

In [573]:
df_tweet_json_clean.head()

,created_at,tweet_id,id_str,full_text,truncated,text_length,entities,extended_entities,source,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,in_reply_to_user_id_str,in_reply_to_screen_name,user,geo,coordinates,place,contributors,is_quote_status,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,possibly_sensitive_appealable,lang,retweeted_status,quoted_status_id,quoted_status_id_str,quoted_status_permalink,quoted_status
0,Tue Aug 01 16:23:56 +0000 2017,892420643555336193,892420643555336193,This is Phineas. He's a mystical boy. Only eve...,False,85,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 892420639486877696, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,7373,35072,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN
1,Tue Aug 01 00:17:27 +0000 2017,892177421306343426,892177421306343426,This is Tilly. She's just checking pup on you....,False,138,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 892177413194625024, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,5494,30366,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN
2,Mon Jul 31 00:18:03 +0000 2017,891815181378084864,891815181378084864,This is Archie. He is a rare Norwegian Pouncin...,False,121,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 891815175371796480, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,3632,22829,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN
3,Sun Jul 30 15:58:51 +0000 2017,891689557279858688,891689557279858688,This is Darla. She commenced a snooze mid meal...,False,79,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'media': [{'id': 891689552724799489, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,7550,38342,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN
4,Sat Jul 29 16:00:24 +0000 2017,891327558926688256,891327558926688256,This is Franklin. He would like you to stop ca...,False,138,"{'hashtags': [{'text': 'BarkWeek', 'indices': ...","{'media': [{'id': 891327551943041024, 'id_str'...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,None,None,"{'id': 4196983835, 'id_str': '4196983835', 'na...",None,None,None,None,False,8137,36622,False,False,False,False,en,NaN,NaN,NaN,NaN,NaN

### Quality

#### Delete duplicated column, full_text source from tweet_json table. Also get rid of id_str which is the same as tweet_id but in string. It is the same information in other format. Delete also created_at, truncated, entities, extended_entities they show duplicated information. Delete because their value is the same for all rows, it is none of nan: in_reply_to_status_id, in_reply_to_status_id_str, in_reply_to_user_id, in_reply_to_user_id_str, in_reply_to_screen_name, geo, coordinates, place, contributors, is_quote_status, favorited, retweeted, possibly_sensitive, possibly_sensitive_appealable, lang, user,retweeted_status, quoted_status_id, quoted_status_id_str, quoted_status_permalink, quoted_status

##### Define
using drop to delete all redundant columns mentioned above

##### Code

In [574]:
df_tweet_json_clean = df_tweet_json_clean.drop(['created_at','source','id_str','full_text','truncated' ,'entities','user','extended_entities', 'in_reply_to_status_id', 'in_reply_to_status_id_str', 'in_reply_to_user_id', 'in_reply_to_user_id_str', 'in_reply_to_screen_name', 'geo', 'coordinates', 'place', 'contributors', 'is_quote_status', 'favorited', 'retweeted', 'possibly_sensitive', 'possibly_sensitive_appealable', 'lang', 'retweeted_status', 'quoted_status_id', 'quoted_status_id_str', 'quoted_status_permalink', 'quoted_status'], axis=1)

##### Test

In [575]:
df_tweet_json_clean.head(1)

             tweet_id  text_length  retweet_count  favorite_count
0  892420643555336193           85           7373           35072

### Tidiness

#### create master archive

##### Define
Merge the three tables(df_twitter_archive_enhanced_clean,df_image_predictions_clean ,df_tweet_json_clean) into one master data file using merge 'twitter_archive_master.csv'

##### Code

In [576]:
merged1 = pd.merge(left=df_twitter_archive_enhanced_clean, right=df_image_predictions_clean, on="tweet_id")

In [577]:
merged2 = pd.merge(left=merged1, right=df_tweet_json_clean, on="tweet_id")

##### Test

In [578]:
merged2.head(1)

,tweet_id,timestamp,source,text,expanded_urls,rating,name,dog_stage,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog,text_length,retweet_count,favorite_count
0,892420643555336193,2017-08-01 16:23:56+00:00,Twitter for iPhone,This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,Phineas,None,https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg,1,orange,0.097049,False,bagel,0.085851,False,banana,0.07611,False,85,7373,35072

#### Create master archive

In [579]:
# storing the data in csv format 
merged2.to_csv(r'twitter_archive_master.csv', index = False)

In [580]:
merged2.head(1)

,tweet_id,timestamp,source,text,expanded_urls,rating,name,dog_stage,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog,text_length,retweet_count,favorite_count
0,892420643555336193,2017-08-01 16:23:56+00:00,Twitter for iPhone,This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,Phineas,None,https://pbs.twimg.com/media/DGKD1-bXoAAIAUK.jpg,1,orange,0.097049,False,bagel,0.085851,False,banana,0.07611,False,85,7373,35072

## Summary

Quality

1.Delete columns unnecessary columns because they do not add value to the analysis

2.df_twitter_archive_enhanced: timestamp is an object string and should be a date

3.df_twitter_archive_enhanced: Clean source and leave only the name of the source

4.create a new variable dog_stage and delete all other columns: doggo, floofer, pupper, puppo

5.display_text_range in df_tweet_json table only use the end as that counts the number of characters

6.In columns p1, p2 and p3 in df_image_predictions_clean some capitalized and others lower case

7.In df_tweet_json_clean table change column name id to tweet_id as the other tables

8.Change the column name to something more descriptive text_length

Tidiness

1.create master archive - Merge the three tables(df_twitter_archive_enhanced_clean,df_image_predictions_clean ,df_tweet_json_clean) into one master data file using merge 'twitter_archive_master.csv'

2.create only one column for rating